version: '2.2'

services:
    postgres:
        image: postgres:9.6
        environment:
          POSTGRES_DB: symfony
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - "5432"
        expose:
          - "5432"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -Uuser -dsymfony"]
          interval: 20s
          timeout: 5s
          retries: 20

    mysql:
        image: mysql:${MYSQL_VERSION:-5.5}
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=symfony
        healthcheck:
          test: ["CMD-SHELL", "mysqladmin ping"]
          interval: 30s
          timeout: 5s
          retries: 30
        ports:
          - "3306"
        expose:
          - "3306"
